In [1]:
import json
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd

In [2]:
def convert_from_json_to_dataframe(file_path, record_path=['data', 'paragraphs', 'qas', 'answers']):
    file = json.loads(open(file_path).read())
    js = pd.json_normalize(file, record_path)
    m = pd.json_normalize(file, record_path[:-1])
    r = pd.json_normalize(file, record_path[:-2])
    index = np.repeat(r['context'].values, r.qas.str.len())
    m['context'] = index
    data = m[['id', 'question', 'context', 'answers']].set_index('id').reset_index()
    data['context_id'] = data['context'].factorize()[0]
    return data
    

train_file_path = './train-v2.0.json'
df = convert_from_json_to_dataframe(train_file_path)
df

,id,question,context,answers,context_id
0,56be85543aeaaa14008c9063,When did Beyonce start becoming popular?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': 'in the late 1990s', 'answer_start':...",0
1,56be85543aeaaa14008c9065,What areas did Beyonce compete in when she was...,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': 'singing and dancing', 'answer_start...",0
2,56be85543aeaaa14008c9066,When did Beyonce leave Destiny's Child and bec...,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': '2003', 'answer_start': 526}]",0
3,56bf6b0f3aeaaa14008c9601,In what city and state did Beyonce grow up?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': 'Houston, Texas', 'answer_start': 166}]",0
4,56bf6b0f3aeaaa14008c9602,In which decade did Beyonce become famous?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': 'late 1990s', 'answer_start': 276}]",0
...,...,...,...,...,...
130314,5a7e070b70df9f001a875439,Physics has broadly agreed on the definition o...,"The term ""matter"" is used throughout physics i...",[],19028
130315,5a7e070b70df9f001a87543a,Who coined the term partonic matter?,"The term ""matter"" is used throughout physics i...",[],19028
130316,5a7e070b70df9f001a87543b,What is another name for anti-matter?,"The term ""matter"" is used throughout physics i...",[],19028
130317,5a7e070b70df9f001a87543c,Matter usually does not need to be used in con...,"The term ""matter"" is used throughout physics i...",[],19028
130318,5a7e070b70df9f001a87543d,What field of study has a variety of unusual c...,"The term ""matter"" is used throughout physics i...",[],19028

In [3]:
df.isna().sum()

id            0
question      0
context       0
answers       0
context_id    0
dtype: int64

In [4]:
df.columns

Index(['id', 'question', 'context', 'answers', 'context_id'], dtype='object')

In [5]:
df = df[['question','context', 'answers']]

In [6]:
df.head()

,question,context,answers
0,When did Beyonce start becoming popular?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': 'in the late 1990s', 'answer_start':..."
1,What areas did Beyonce compete in when she was...,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': 'singing and dancing', 'answer_start..."
2,When did Beyonce leave Destiny's Child and bec...,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': '2003', 'answer_start': 526}]"
3,In what city and state did Beyonce grow up?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': 'Houston, Texas', 'answer_start': 166}]"
4,In which decade did Beyonce become famous?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"[{'text': 'late 1990s', 'answer_start': 276}]"

In [7]:
answer_col = []
for j in range(0, 130319):
    answer_list = []
    for i in range(0,len(df['answers'].iloc[j])):
        answer_list.append(df['answers'].iloc[j][i]['text'])
    answer_col.append(answer_list)

In [8]:
df['answers'] = answer_col
df['answers'] = df['answers'].str[0]
df.head()

/tmp/ipykernel_14286/1609599173.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['answers'] = answer_col
/tmp/ipykernel_14286/1609599173.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['answers'] = df['answers'].str[0]

,question,context,answers
0,When did Beyonce start becoming popular?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,in the late 1990s
1,What areas did Beyonce compete in when she was...,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,singing and dancing
2,When did Beyonce leave Destiny's Child and bec...,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,2003
3,In what city and state did Beyonce grow up?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"Houston, Texas"
4,In which decade did Beyonce become famous?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,late 1990s

In [9]:
df.describe()

,question,context,answers
count,130319,130319,86821
unique,130217,19029,64763
top,In what year did World War II start?,"Victoria married her first cousin, Prince Albe...",three
freq,3,30,231

In [10]:
df.isna().sum()

question        0
context         0
answers     43498
dtype: int64

In [11]:
df = df.dropna(axis=1)
df.isna().sum()

question    0
context     0
dtype: int64

In [12]:
df.shape

(130319, 2)

In [13]:
midpoint = int(len(df) / 2)
shuffle_rows = df.index[midpoint:]
df["pair"] = 1
data_to_shuffle = df.loc[shuffle_rows-1, 'context'].to_numpy()
np.random.shuffle(data_to_shuffle)
df.loc[shuffle_rows, 'context'] = data_to_shuffle
df.loc[shuffle_rows, 'pair'] = 0

In [14]:
df.shape

(130319, 3)

In [15]:
df.pair.value_counts()

0    65160
1    65159
Name: pair, dtype: int64

In [16]:
df = df.sample(frac=1).reset_index(drop=True)

In [17]:
df.head(20)

,question,context,pair
0,What is the Arabic term for the surface-level ...,For many years Labour held to a policy of not ...,0
1,What previous movement is post-punk often iden...,The very large and ornate School Hall and Scho...,0
2,What is the reason for studying the promotion ...,China's network security and information techn...,1
3,As of when did Christianity have about 2.4 mil...,"As of the early 21st century, Christianity has...",1
4,What is the main European basketball club?,Each successive rank gave its holder greater p...,0
5,How does the color temperature differ for phot...,"In flood lamps used for photographic lighting,...",1
6,Who defined mammalian as the crown group mammals?,"In an influential 1988 paper, Timothy Rowe def...",1
7,Who was influentual among European ethnologists?,Cubism was relevant to an architecture seeking...,0
8,When did the emperor Constantine lose rule ov...,The Endangered Species Conservation Act (P. L....,0
9,What did the state council set up in 2008?,"In 2008, State Council established a counterpa...",1
10,What was the claim that the lawsuit was based on?,"In February 2007, Texas MP3 Technologies sued ...",1
11,What do Muslims call the month when they fast ...,In some Muslim countries DST is temporarily ab...,1
12,The land bridge connecting two European contin...,The most reliable method for assessing pain in...,0
13,What instrument does the mandolin share the sa...,It is possible to use the impedance matching c...,0
14,In what year didn't the papacy return to Rome?,Avignon was the seat of the papacy from 1309 t...,1
15,How is hydrogen used as a food additive?,"In more recent applications, hydrogen is used ...",1
16,The PDOT lost four seats in what election?,The Nigerian film industry is known as Nollywo...,0
17,Where are the group elders located?,Apart from the passing of noble titles or rank...,0
18,What has a golden band around its circumference?,The first Digimon anime introduced the Digimon...,0
19,What Asian war threatened Canada?,"Prior to Confederation in 1867, residents of t...",1

In [18]:
df.to_csv('./train.csv')

In [19]:
import gensim
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
import torch
from transformers import AutoTokenizer, AutoModel
from transformers import GPT2Tokenizer, GPT2Model
from scipy.spatial.distance import cosine

In [21]:
def calculate_lsa_score(question, context):
    vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = vectorizer.fit_transform([question, context])
    svd = TruncatedSVD(n_components=2)
    lsa_matrix = svd.fit_transform(tfidf_matrix)
    lsa_score = 1 - cosine(lsa_matrix[0], lsa_matrix[1])
    return lsa_score


import gensim.downloader as api
word_vectors = api.load("glove-wiki-gigaword-100")
#word_vectors = KeyedVectors.load_word2vec_format('glove-wiki-gigaword-200', binary=False)

def calculate_embedding_score(question, context):
    question_vec = np.mean([word_vectors[word] for word in question.split() if word in word_vectors], axis=0)
    context_vec = np.mean([word_vectors[word] for word in context.split() if word in word_vectors], axis=0)
    embedding_score = 1 - cosine(question_vec, context_vec)
    return embedding_score

In [22]:
dfx = df.iloc[0:10,:]
dfx.head()

,question,context,pair
0,What is the Arabic term for the surface-level ...,For many years Labour held to a policy of not ...,0
1,What previous movement is post-punk often iden...,The very large and ornate School Hall and Scho...,0
2,What is the reason for studying the promotion ...,China's network security and information techn...,1
3,As of when did Christianity have about 2.4 mil...,"As of the early 21st century, Christianity has...",1
4,What is the main European basketball club?,Each successive rank gave its holder greater p...,0

In [23]:
# Apply functions to each row in the DataFrame
dfx['lsa_score'] = dfx.apply(lambda x: calculate_lsa_score(x['question'], x['context']), axis=1)
dfx['embedding_score'] = dfx.apply(lambda x: calculate_embedding_score(x['question'], x['context']), axis=1)

# Print the DataFrame with added scores
dfx.head(10)

/tmp/ipykernel_14286/3153694269.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfx['lsa_score'] = dfx.apply(lambda x: calculate_lsa_score(x['question'], x['context']), axis=1)
/tmp/ipykernel_14286/3153694269.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfx['embedding_score'] = dfx.apply(lambda x: calculate_embedding_score(x['question'], x['context']), axis=1)

,question,context,pair,lsa_score,embedding_score
0,What is the Arabic term for the surface-level ...,For many years Labour held to a policy of not ...,0,0.000000e+00,0.945736
1,What previous movement is post-punk often iden...,The very large and ornate School Hall and Scho...,0,-2.220446e-16,0.890139
2,What is the reason for studying the promotion ...,China's network security and information techn...,1,4.795455e-01,0.966240
3,As of when did Christianity have about 2.4 mil...,"As of the early 21st century, Christianity has...",1,1.269197e-01,0.940693
4,What is the main European basketball club?,Each successive rank gave its holder greater p...,0,1.110223e-16,0.870995
5,How does the color temperature differ for phot...,"In flood lamps used for photographic lighting,...",1,1.245930e-01,0.895302
6,Who defined mammalian as the crown group mammals?,"In an influential 1988 paper, Timothy Rowe def...",1,1.935427e-01,0.927698
7,Who was influentual among European ethnologists?,Cubism was relevant to an architecture seeking...,0,-2.220446e-16,0.814359
8,When did the emperor Constantine lose rule ov...,The Endangered Species Conservation Act (P. L....,0,0.000000e+00,0.906157
9,What did the state council set up in 2008?,"In 2008, State Council established a counterpa...",1,1.271921e-01,0.939218